# Generated by Django 5.1 on 2024-09-05 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SegEstrada",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("long_start", models.FloatField()),
                ("lat_start", models.FloatField()),
                ("long_end", models.FloatField()),
                ("lat_end", models.FloatField()),
                ("length", models.FloatField()),
                ("speed", models.FloatField()),
                ("tempo_reg", models.DateTimeField(auto_now_add=True)),
                ("views_count", models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
